title: quiet misdreavus microblog
name: quiet misdreavus microblog
description: short-ish notes about day-to-day life as a quiet misdreavus
baseurl: ""
url: "https://micro.quietmisdreavus.net"

# Fill this out to include author information in RSS/OpenGraph info
author: QuietMisdreavus

exclude: ["README.md"]

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty
