title: quiet misdreavus microblog
name: quiet misdreavus microblog
description: short-ish notes about day-to-day life as a quiet misdreavus
baseurl: ""
url: "https://micro.quietmisdreavus.net"

# Fill this out to include author information in RSS/OpenGraph info
author: QuietMisdreavus

exclude: ["README.md"]

date_format: "%Y-%m-%d"

# Build settings
kramdown:
  input: GFM
permalink: pretty

category_descriptions:
  self: "personal posts, or posts about social topics"
  code: "posts about programming projects or concepts"
  trans: "personal posts specifically about gender or the trans experience"
  games: "posts about video game-related topics"
